#!/usr/bin/env sh

set -ue

diff="git diff --diff-filter=ACMR --cached --name-only"

files="$($diff -- *.html *.css *.ts *.tsx *.js *.jsx *.json | xargs)"
if test -n "$files"; then
	# shellcheck disable=SC2086
	npm run --silent format -- --log-level warn --check $files
fi

files="$($diff -- *.ts *.tsx *.js *.jsx | xargs)"
if test -n "$files"; then
	# shellcheck disable=SC2086
	npm run --silent lint -- $files
fi
